<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        function increase(number) {
            const promise = new Promise((resolve, reject) => {
                setTimeout(() =>{
                    const result = number + 10;

                    if(result > 50) {
                        const e = new Error('NumberTooBig');  //예외 객체
                        return reject(e);
                    }

                    return resolve(result);
                }, 1000);
            });

            return promise;
        };
        /*
            await의 두 가지 기능
            1. await이 달린 함수(increase)의 결과인 promise 객체에 담긴 결과(성공/실패)를 반환한다.
            (then()과 유사)
            2. await이 달린 비동기 처리들은 그들 간에는 동기식으로 동작하게 된다.
            (앞선 비동기의 결과로 다음 비동기 함수를 실행할 수 있다.)

            then 메소드처럼 callback함수는 필요 없지만 전체를 감싸는 async 함수는 반드시 필요하다.
            (주의: await를 쓰기 위해 함수에 async를 추가하면 함수의 반환값이 promise가 된다.)
        */
        async function run() {
            console.log('run start ----------------------')
            let result = await increase(0);
            console.log(result);
            
            result = await increase(result);
            console.log(result);
            
            result = await increase(result);
            console.log(result);
            
            result = await increase(result);
            console.log(result);
            
            result = await increase(result);
            console.log(result);
            try{
            result = await increase(result); } catch(e){
console.log('테스트',e);
            }
            console.log('run end ----------------------')
        }

        run();

        /* await을 사용 하지 않으면 동기화가 되지 않아 5개의 작업이 동시에 실행 하게 되어 결과가 1초에 1개씩 반환되는게 아닌
            5개의 결과값이 동시에 출력 하게 됨 그 결과 이전 작업의 결과값을 받아서 출력 할 수 없게 됨
        */
        async function run1() {
            console.log('run1 start----------------------')
            let result =  increase(0);
            console.log(result);
            
            result =  increase(result).then(result => console.log(`then의 콜백함수에 넘어온 result : ${result}`));
            console.log(result);
            
            result =  increase(result).then(result => console.log(`then의 콜백함수에 넘어온 result : ${result}`));
            console.log(result);
            
            result =  increase(30).then(result => console.log(`then의 콜백함수에 넘어온 result : ${result}`));
            console.log(result);
            
            result =  increase(40).then(result => console.log(`then의 콜백함수에 넘어온 result : ${result}`));
            console.log(result);
            console.log('run1 end----------------------')
        }

        run1();

        // async 함수는 결과를 promise 객체로 반환
        async function run2() {
            // let result = await increase(0);
            // console.log(result);
            
            return -1;
        }
        

        console.log(run2());

        run2().then(result => console.log(`async의 결과인 promise에 담긴 값: ${result}`));

    </script>
</body>
</html>